### ISSUE TITLE
Allay to-do

### ISSUE THREAD

**Issue by BluePhoenixLOL** [Osmiooo/wildmod#169]
- [ ] Allay texture and model matches bedrock
- [ ] Allays spawn in cages in pillager outposts and woodland mansions
- [ ] Allay GameEvent listener for noteblocks 
- [ ] If an Allay holds an item it got from a player, it will follow that player
- [ ] The Allay is able to drop items at nearby Note Blocks
- [ ] When playing a Note Block near an Allay, that Note Block becomes the Allays favourite Note Block for 30 seconds, and the Allay will attempt to drop off items at the Note Block rather than at the player
- [ ] If an Allay has items in its inventory, it will attempt to give them to its owner

**Comment by Gamerdacchund99** [comment]
the first one should _maybe_ be easy.
