### ISSUE TITLE
To-do before first 1.18.2 release

### ISSUE THREAD

**Issue by Treetrain1** [Osmiooo/wildmod#183]
These are things that need to be fixed before the first 1.18.2 release. Ancient City generation should be high priority and so should the Warden and Allay’s AI. Feel free to add anything to this list.

**Worldgen**

These issues should probably be fixed first because worldgen is permanent when it first generates.

- [ ] Ancient cities should generate at the bottom of the world at y = -54
- [ ] Ancient cities need to generate from classes instead of datapacks. This may also remove the experimental world warning on world join.
- [ ] Ancient cities should generate a beard box, a massive pocket of air, around it.
- [ ] Port new Mangrove Swamp surface rules - maybe easy, search “MANGROVE_SWAMP” in VanillaSurfaceRules in the latest snapshot.

**Entities**

- [ ] Warden and Allay need their updateEventHandler() method to be called and run. (will probably fix their AI) - #182 
- [ ] Warden’s anger system needs to work. - maybe caused by updateEventHandler? - #182 
- [ ] Warden’s features need to render. (Heartbeat, Bioluminescent layer, emissive spots) - no clue how to fix
- [ ] Frogs should be able to spawn without erroring. - something errors in TrackedDataHandler idk

**Sculk Blocks**

- [ ] Sculk Catalysts should use the new sculk patch system and should produce sculk whenever an entity dies around it.
- [ ] Only players should activate Sculk Shriekers. - probably easy, probably just needs `if (entity instanceof PlayerEntity)`

**Non-Sculk Blocks**

- [ ] Mangrove signs should allow the player to write. - almost working, write gui appears but only lasts for a few frames. - #93
