### ISSUE TITLE
Miscellaneous Entity Bugs

### ISSUE THREAD

**Issue by AViewFromTheTop** [Osmiooo/wildmod#65]
- [x] Make Warden overlay be able to match secret texture (HELP WANTED) - #69
- [x] Make Fireflies one big entity, each firefly is an individual particle (ON HOLD)
- [ ] Fix Frogs (HELP WANTED) #96
- [x] Make Warden overlay darker in lighter areas (HELP WANTED) - #69

**Comment by AViewFromTheTop** [comment]
Closing this issue as pretty much all of these are help wanted, and the title can't do a good job at describing all of these at once

**Comment by MerpisMe** [comment]
Reopening as it acts as a good todo list

**Comment by BluePhoenixLOL** [comment]
fix frooooooooooooogs

**Comment by BluePhoenixLOL** [comment]
how... hmmm

**Comment by AViewFromTheTop** [comment]
Surpassed by #96.
